# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alloweduserreferrals',
            table='allowed_user_referrals',
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choices',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='questionnaire',
            table='questionnaires',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userchoice',
            table='user_choices',
        ),
        migrations.AlterModelTable(
            name='usertype',
            table='user_types',
        ),
    ]
