# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wq_app', '0002_auto_20170416_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_state',
            field=models.CharField(choices=[('AD', 'Administrator'), ('RF', 'Referrer'), ('NR', 'Normal user'), ('DL', 'Deleted')], default='NR', max_length=30),
        ),
    ]
