# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wq_app', '0003_auto_20170416_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_state',
            field=models.CharField(choices=[('AC', 'Activated'), ('UA', 'Unactivated')], default='UA', max_length=30),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.CharField(choices=[('AD', 'Administrator'), ('RF', 'Referrer'), ('NR', 'Normal user'), ('DL', 'Deleted')], default='NR', max_length=50),
        ),
    ]
