# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wq_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wq_app', '0004_auto_20170416_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_number', models.CharField(max_length=20, null=True)),
                ('activation_key', models.CharField(max_length=50, null=True)),
                ('key_expiration', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'usermeta',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='alloweduserreferrals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wq_app.UserMeta'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='submitter',
            field=models.ForeignKey(on_delete=models.SET(wq_app.models.get_sentinel_user), to='wq_app.UserMeta'),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wq_app.UserMeta'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.AddField(
            model_name='usermeta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_meta', to=settings.AUTH_USER_MODEL),
        ),
    ]
