# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wq_app', '0005_auto_20170416_2325'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermeta',
            table='users_meta',
        ),
    ]
